name: CI/CD Pipeline for Microservices

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Docker (Docker è già preinstallato)
    - name: Log in to Docker Hub (if needed)
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin || true

    # Step 3: Build and run services with Docker Compose
    - name: Build and start services with Docker Compose
      run: docker compose -f src/docker-compose.yml up --build -d

    # Step 4: Run unit tests
    - name: Run unit tests for calc
      run: docker compose exec calc pytest app_test.py --disable-warnings

    - name: Run unit tests for string
      run: docker compose exec string pytest app_test.py --disable-warnings

    # Step 5: Run integration tests
    - name: Run integration tests with Newman
      run: docker compose exec gateway newman run /test/integration.postman_collection.json

    # Step 6: Tear down services
    - name: Stop and remove services
      if: always()
      run: docker compose -f src/docker-compose.yml down
